### ISSUE TITLE
Swift package-  swift-tools-version too old

### ISSUE THREAD

**Issue by Bill-Niz** [safx/emoji-swift#25]
package at 'https://github.com/safx/Emoji-Swift.git' @ 4a5b86725fe67019f3df9a0bf3f542d34d4058e4 is using Swift tools version 3.1.0 which is no longer supported; consider using '// swift-tools-version:5.3' to specify the current tools version

**Comment by safx** [comment]
@Bill-Niz thank you for your suggestion. I added the comment, thanks.
