### ISSUE TITLE
Inconsistency in codes

### ISSUE THREAD

**Issue by SergeyPetrachkov** [safx/emoji-swift#8]
if we open [this site](https://emojipedia.org/keycap-digit-one/ )
we see that 'one' is actually 
`"one" : "\u{0031}\u{FE0F}\u{20E3}" `
not the 
`"one" : "\u{0031}\u{20e3}"`

And if you insert "one" emoji into text from your apple device you'll get _"\u{0031}\u{FE0F}\u{20E3}"_ . But [this site](https://apps.timwhitlock.info/emoji/tables/unicode) matches your version of emoji dictionary.

Any ideas? Should them be replaced?

**Comment by SergeyPetrachkov** [comment]
How it should look like ![how_it_should_look_like](https://user-images.githubusercontent.com/7995896/27669734-b0a71e6e-5cb2-11e7-866f-908e3c6062ae.png)
How it works ![problem_how_it_works_now](https://user-images.githubusercontent.com/7995896/27669735-b0cbaedc-5cb2-11e7-85ed-ce5f00b97df6.jpg)
workaround <img width="700" alt="screen" src="https://user-images.githubusercontent.com/7995896/27669736-b0e21956-5cb2-11e7-84bf-9c95a057ea7c.png">

**Comment by safx** [comment]
Sorry about the lazy reply.
Some emojis have variations with `VARIATION SELECTOR-16` (U+FE0F).

Please see #9 .
